name: Test Inductor OpInfo Backed

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-inductor-opinfo:
    strategy:
      fail-fast: false
      matrix:
        pytorch_test_range: ["PYTORCH_TEST_RANGE_START=0 PYTORCH_TEST_RANGE_END=100", 
                    "PYTORCH_TEST_RANGE_START=100 PYTORCH_TEST_RANGE_END=200",
                    "PYTORCH_TEST_RANGE_START=200 PYTORCH_TEST_RANGE_END=300",
                    "PYTORCH_TEST_RANGE_START=300 PYTORCH_TEST_RANGE_END=400",
                    "PYTORCH_TEST_RANGE_START=400 PYTORCH_TEST_RANGE_END=500",
                    "PYTORCH_TEST_RANGE_START=500 PYTORCH_TEST_RANGE_END=600",
                    "PYTORCH_TEST_RANGE_START=600 PYTORCH_TEST_RANGE_END=700"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - run: make setup_nightly
    - run: make develop
    - run: PYTORCH_ALL_SAMPLES=1 ${{ matrix.pytorch_test_range }} pytest test/inductor/test_torchinductor_opinfo.py -s

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
